name: Verify Mongo & Django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: octofit_tracker.settings

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Django check
      run: |
        python manage.py check
